server:
  port: 8081
spring:
  #data:
  #  mongodb:
  #    host: localhost
  #    port: 27017
  #    database: orders
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191
